# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-15 08:24
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investigation', '__first__'),
        ('maps', '0027_auto_20190516_0909'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0027_auto_20170801_1228_squashed_0037_auto_20190222_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Narratives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name=b'Titulo')),
                ('narrative', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name=b'Contenido')),
                ('ext_url', models.URLField(blank=True, help_text=b'Escriba la URL del recurso, s\xc3\xb3lo si es externo', null=True, verbose_name=b'Liga al recurso')),
                ('description', models.TextField(max_length=250, verbose_name=b'Descripcion')),
                ('coverage', models.CharField(help_text=b'Busque la ubicacion deseada o mueva el marcador', max_length=150, null=True, verbose_name=b'Cobertura')),
                ('image', models.ImageField(null=True, upload_to=b'images/', verbose_name=b'Imagen')),
                ('public', models.BooleanField(default=False, verbose_name=b'Publicar')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('count_row', models.IntegerField(blank=True, default=0, null=True, verbose_name=b'contador')),
                ('allow_comments', models.BooleanField(default=False, verbose_name=b'Permite que los usuarios comenten en tu narrativa')),
                ('authorize_comments', models.BooleanField(default=False, verbose_name=b'Autoriza lo comentarios via e-mail')),
                ('author', models.ManyToManyField(blank=True, related_name='narratives_author', to=settings.AUTH_USER_MODEL, verbose_name=b'Autor')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.TopicCategory')),
                ('investigation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investigation.Investigation', verbose_name=b'Investigacion')),
                ('maps', models.ManyToManyField(blank=True, null=True, related_name='narratives_maps', to='maps.Map', verbose_name=b'Mapas relacionados')),
                ('publisher', models.ManyToManyField(blank=True, related_name='narratives_publisher', to=settings.AUTH_USER_MODEL, verbose_name=b'Editor')),
            ],
        ),
    ]
