# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-13 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('ms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='microsite',
            name='topic',
            field=models.ManyToManyField(blank=True, help_text=b'Seleccione las tematicas.', null=True, to='blog.Topic', verbose_name=b'Tematicas'),
        ),
    ]
